# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterdata',
            name='content',
            field=models.CharField(default='Default Value', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='lang',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='tweet_id',
            field=models.CharField(default='000000000000', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
    ]
