# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20160324_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='tweet_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
