# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20160324_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_text', models.CharField(choices=[(b'POS', b'Positive'), (b'NEG', b'Negative'), (b'UND', b'Undecidable'), (b'IRR', b'Irrelevant')], default=b'UND', max_length=3)),
                ('votes', models.IntegerField(default=0)),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.TwitterData')),
            ],
        ),
    ]
