# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='tweet_id',
            new_name='tweet',
        ),
    ]
