# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20160325_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
