# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_twitterdata_tweet_sentiment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetFile',
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='sentiment1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='sentiment2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='sentiment3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
